name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install azureml-core azureml-sdk

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Azure CLI
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push Docker image
      run: |
        az acr build --registry ${{ secrets.ACR_NAME }} --image myflaskapp:latest .

    - name: Deploy to Azure ML
      run: |
        python deploy_to_aml.py
